# Gestionado por Copier: no editar a mano. Registra los rasgos del proyecto.
_commit: v0.8.1
_src_path: gh:EmmanuelIsaiasGuizarBayardo/plantilla-proyecto
autor_apellidos: Guízar-Bayardo
autor_nombres: Emmanuel Isaías
contenido_didactico: false
datos_de_personas: true
descripcion: 'Detección de enfermedad de Parkinson en EEG: validación por sujetos
    y transferibilidad a Emotiv EPOC X.'
entrada_propia: false
investigacion: true
nombre_proyecto: Tesis_EEG_Parkinson
operacion_en_vivo: false
organizacion_github: EmmanuelIsaiasGuizarBayardo
proyecto_dunne: false
python_version: '3.12'
senal_externa: false
usa_gpu: false
